Suite = "ed25519"
Hosts = ["127.0.0.1:2000", "127.0.0.1:2010", "127.0.0.1:2020"]
AggPubKey = "wtvPtBGZ9mgcK89zuyhIllRqJXPb/t3Lal6p50x2eZw="

[Tree]
  Name = "127.0.0.1:2000"
  PriKey = ""
  PubKey = "TmkSi32bJ8zwX+BU/jdpNcn97r4mMQVXoaKSat4/tAM="

  [[Tree.Children]]
    Name = "127.0.0.1:2010"
    PriKey = ""
    PubKey = "DyBQIKOjuqGJBItrzzSzFu7kxz2FNFu3qZ+UV0J8IEU="

  [[Tree.Children]]
    Name = "127.0.0.1:2020"
    PriKey = ""
    PubKey = "kavVl9VBtLAI8Aoc+wHtUrJ6q2J0FQWYJA9Y5e6j9AI="
