Suite = "ed25519"
Hosts = ["localhost:2000", "localhost:2010", "localhost:2020"]
AggPubKey = "YUvEEgjtf/8Nl95ESOQOaazlZsp1j920FHGNKUTyZKc="

[Tree]
  Name = "localhost:2000"
  PriKey = ""
  PubKey = "rMkwsT4rhLxqTkFgWFWVBx+dIGmtY6ANXyF2XGfYg0g="

  [[Tree.Children]]
    Name = "localhost:2010"
    PriKey = ""
    PubKey = "WhVUW/ha0Nnh2bFHkX2vBl72SpMC3u4QI+GBXtSMSaY="

  [[Tree.Children]]
    Name = "localhost:2020"
    PriKey = ""
    PubKey = "p3UXRgRz3LfDReNm9KX6lvNaZateehxsEx+YGFaTOtw="
