Suite = "25519"
Hosts = ["127.0.0.1:2000", "127.0.0.1:2020", "127.0.0.1:2030"]
AggPubKey = "TUkafmfhgSBTe7pEyCa1zGYyxfrb9EjBR6pV2qxIlaA="

[Tree]
  Name = "127.0.0.1:2000"
  PriKey = ""
  PubKey = "VY7y/Wky+FyKmagO/tdzGnWviCWp+88Foc6rTN/M1PA="

  [[Tree.Children]]
    Name = "127.0.0.1:2020"
    PriKey = ""
    PubKey = "iz39fnBaAkmA9gLkgk9DBE6fep8HzJYTAcRAt+DlfwI="

  [[Tree.Children]]
    Name = "127.0.0.1:2030"
    PriKey = ""
    PubKey = "kczmzeuHaC6a5xKdQYFYx+UCdpmCa3MQ8ty9nOnw7SA="
