Suite = "ed25519"
Hosts = ["127.0.0.1:2000", "127.0.0.1:2010", "127.0.0.1:2020"]

[Tree]
  Name = "127.0.0.1:2000"
  PriKey = ""
  PubKey = "82W1R7yRVuOAKcsBxaSQ2mSFN6ukaq1+T57z5qmiE4s="

  [[Tree.Children]]
    Name = "127.0.0.1:2010"
    PriKey = ""
    PubKey = "2mBOKH6Gr45AAoYIGzpLOlF5868/J79M2Zni2Ya15TY="

  [[Tree.Children]]
    Name = "127.0.0.1:2020"
    PriKey = ""
    PubKey = "D/TH9+3T9RkbQeJRCMp2e4yGIVmVq8mRYUrXAjxx/J8="
