language: go

install:
  - go get -t ./...
  - go get github.com/dedis/Coding || true
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/dedis/goveralls

script:
  - go test -p=1 -short ./...
  - ( cd conode && ./test.sh )
  - ( cd scmgr && ./test.sh )
  - make test

notifications:
  email: false
