matrix:
  include:
    - language: go

      install:
        - go get -t ./...
        - go get github.com/dedis/Coding || true

      script:
        - make test

      notifications:
        email: false

    - language: node_js

      node_js:
        - "lts/*"
        - "8"
        - "7"

      env:
        - TEST_DIR=external/js/cothority
        - TEST_DIR=external/js/kyber

      script: cd $TEST_DIR && npm install && npm run test && npm run build

      after_success:
        - npm run coveralls

      notifications:
        email: false
