language: node_js

node_js:
  - "lts/*"
  - "8"

env:
  - TEST_DIR=cothority
  - TEST_DIR=kyber

before_install:
  - export GOPATH="$(pwd)/../../../../"
  - echo $GOPATH
  - cd external/js/

script: cd $TEST_DIR && npm install && npm run test && npm run build

after_success:
  - npm run coveralls

notifications:
  email: false

matrix:
  include:
    - language: go

      install:
        - go get -t ./...
        - go get github.com/dedis/Coding || true

      before_install:
        - cd $TRAVIS_BUILD_DIR

      script:
        - make test

      notifications:
        email: false
