matrix:
  include:
    - language: go

      install:
        - go get github.com/dedis/onet
        - git -C ../onet checkout byzgen_poc
        - go get -t ./...
        - go get github.com/dedis/Coding || true

      script:
        - make test_fmt
        - make test_lint
        - make test_goveralls

      notifications:
        email: false

    - language: node_js

      node_js:
        - "lts/*"
        - "8"
        - "7"

      before_install:
        - "cd external/js/kyber"

      notifications:
        email: false
