# build script for dedis/cothority libraries
language: go
go:
  - 1.5.2
env:
  global:
    - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/dedis/cothority
before_install:
script:
    - go test -v ./...
    #- go run dedis-travis-script.go
