# build script for dedis/cothority libraries
language: go
go:
  - 1.5.2
before_install:
  - mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/dedis
  - cd $GOPATH/src/github.com/dedis
script:
    - go test -v ./...
    #- go run dedis-travis-script.go
