matrix:
  include:
    - language: go

      install:
        - go get -t ./...
        - go get github.com/dedis/Coding || true
	- git -C ../onet checkout byzgen_poc

      script:
        - make test

      notifications:
        email: false

    - language: node_js

      node_js:
        - "lts/*"
        - "8"
        - "7"

      before_install:
        - "cd external/js/kyber"

      notifications:
        email: false
