# build script for dedis/cothority libraries
language: go
go:
  - 1.6.2
script:
  # If we're in a branch for gopkg.in, switch to that directory and checkout the
  # correct branch
  - if [ ${TRAVIS_BRANCH} == 'v0' ]; then 
#        BRANCH=$( git rev-parse --abbrev-ref HEAD ); 
        GOPKG=$GOPATH/src/gopkg.in/dedis/cothority.v0; 
        rm -rf $GOPKG
        cp -a ../cothority $GOPKG
        cd $GOPKG
#        echo $BRANCH;
#        git checkout $BRANCH;
    fi;
  # formatting:
  - ./gofmt.sh
  # linter:
  - go get -u github.com/golang/lint/golint
  - ./lint.sh
  # check for missing error handling:
  #- go get -u github.com/kisielk/errcheck
  #- ./errcheck.sh
    # do not run any test binary in parallel (see go help build for more info on the -p flag)
  - go test -race -p=1 ./...

notifications:
  email: false
