sudo: required

language: java

services:
  - docker

cache:
  directories:
  - $HOME/.m2

install:
  - go get -t github.com/dedis/cothority/...
  - go get github.com/dedis/Coding || true
  # Because we are using "language: java" the "git clone" is not in the
  # GOPATH. So make a copy of it over where it is supposed to be.
  - git clone . `go env GOPATH`/src/github.com/dedis/onchain-secrets
  - (cd `go env GOPATH`/src/github.com/dedis/onchain-secrets && go get -t ./... )

script:
  - make test_fmt test_lint
  - make docker docker_test
  - go test -v -short ./...
  - (cd external/java; mvn test)

notifications:
  email: false
