[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "1.3.0"

[[constraint]]
  branch = "byzgen_poc"
  name = "github.com/dedis/cothority"

[[constraint]]
  branch = "byzgen_poc"
  name = "github.com/dedis/onet"

[[constraint]]
  name = "github.com/dedis/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "gopkg.in/satori/go.uuid.v1"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

