[[constraint]]
  branch = "byzgen_poc"
  name = "github.com/dedis/kyber"

[[constraint]]
  branch = "byzgen_poc"
  name = "github.com/dedis/cothority"

[[constraint]]
  branch = "byzgen_poc"
  name = "github.com/dedis/onet"


