[[servers]]
  Address = "tcp://127.0.0.1:7002"
  Public = "mkA0EYEqjNMC+jVxtVCPaUI3oWjwt5TNDK8bpXgHL0Q="
  Description = "Conode_1"
[[servers]]
  Address = "tcp://127.0.0.1:7004"
  Public = "ljojlp5FKO05HZRTy5aVAV5kaWWN+0vxfIHLZ3dW79Q="
  Description = "Conode_2"
[[servers]]
  Address = "tcp://127.0.0.1:7006"
  Public = "imd1y9Mp3vey1GdyFy6gk+w0XAuAN7wO34u5rcKiIHI="
  Description = "Conode_3"
