Servers = 2
Simulation = "BizCoinSimulation"
Rounds = 5
BF = 5
BlocksDir = "/Users/gailly/Documents/go/src/github.com/dedis/cothority/simul/runfiles/blocks"

Hosts, Blocksize, TimeoutMs, Fail
30, 1024, 6000, 1
