Login = "nikkolas"
Host = "users.deterlab.net"
Project = "dissent-cs2"
DeployDir = "/Users/gailly/Documents/go/src/github.com/dedis/cothority/deploy/deterlab/remote"
BuildDir = "/Users/gailly/Documents/go/src/github.com/dedis/cothority/deploy/deterlab/build"
DeterDir = "/Users/gailly/Documents/go/src/github.com/dedis/cothority/deploy/deterlab"
TestConnect = false

[Config]
  Nmachs = 8
  Nloggers = 3
  Hpn = 1
  Bf = 8
  Nmsgs = -1
  Rate = 30
  Rounds = 20
  Failures = 0
  RFail = 0
  FFail = 0
  Debug = 1
  RootWait = 10
  App = "schnorr_sign"
  Suite = "ed25519"
