Servers = 2
Simulation = "BizCoinSimulation"
NumClientTxs = 4000000
Rounds = 10
BF = 2
BlocksDir = "/Users/khoffi/go/src/github.com/dedis/cothority/protocols/bizcoin/blocks"

Hosts, Blocksize
2, 1024
