Servers = 37
Simulation = "BizCoinSimulation"
NumClientTxs = 4000000
Rounds = 10
BF = 2
BlocksDir = "/Users/khoffi/go/src/github.com/dedis/cothority/protocols/bizcoin/blocks"

Hosts, Blocksize, TimeoutMs, Fail
2, 1024, 120000, 0
3, 2048, 120000, 1
3, 2048, 120000, 2
