Servers = 2
Simulation = "BizCoinSimulation"
NumClientTxs = 999999999999
Rounds = 10
BF = 10
BlocksDir = "/Users/khoffi/go/src/github.com/dedis/cothority/protocols/bizcoin/blocks"

Hosts, Blocksize, TimeoutMs, Fail
16, 17000, 1200000, 0
