Login = "ineiti"
Host = "users.deterlab.net"
Project = "Dissent-CS"
DeployDir = "/Users/epfl/cothorities/platforms/deterlab/deploy"
BuildDir = "/Users/epfl/cothorities/platforms/deterlab/build"
DeterDir = "/Users/epfl/cothorities/platforms/deterlab"

[Config]
  Nmachs = 5
  Nloggers = 3
  Hpn = 32
  Bf = 4
  Nmsgs = -1
  Rate = 30
  Rounds = 20
  Failures = 0
  RFail = 0
  FFail = 0
  Debug = 1
  App = "stamp"
  Suite = "ed25519"
